---
title: "HW1"
author: "Ziran Xu"
date: "2019/2/5"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Q1
```{r}
data = read.csv("vol_skew.csv")
M=data[1]
vol=as.vector(data[2])/100
s=226.28
k=M*s
r=0.0035
t=1
d1=(log(s/k)+(r+vol^2/2)*t)/(vol*sqrt(t))
d2=d1-vol*sqrt(t)
C=s*mapply(pnorm,d1)-mapply(pnorm,d2)*k*exp(-r*t)
Cprice=cbind(k,vol,C)
mode(Cprice)
colnames(Cprice) = c("k","vol","Price") 
print(Cprice)

```

```{r}
f=function(x,y,x0)
{
  ff=function(x0)
    {
      x=c(0,x)
      y=c(0,y)
      sample=order(x,decreasing=FALSE)
      x=x[sample];y=y[sample]
      i=which(x>x0)[1]
      y0=y[i-1]+(x0-x[i-1])/(x[i]-x[i-1])*(y[i]-y[i-1])
      return(y0)
    }
  return(mapply(ff, x0))
}
Pricing = function(para)
{
  d1=(log(s/para[1])+(r+para[2]^2/2)*t)/(para[2]*sqrt(t))
  d2=d1-para[2]*sqrt(t)
  c=s*mapply(pnorm,d1)-mapply(pnorm,d2)*para[1]*exp(-r*t)
  return(c)
}
dK=5  #set the dk as 5
k_set=seq(from=min(k)+dK,to=400,by=dK)
vol_calculate=f(k[,1],vol[,1],k_set)
price_calculate=apply(cbind(k_set,vol_calculate), 1, Pricing)
pdf=exp(r*t)*(price_calculate[1:(length(price_calculate)-2)]+price_calculate[3:length(price_calculate)]-2*price_calculate[2:(length(price_calculate)-1)])/dK^2
print(vol_calculate)
plot(pdf,type = 'l')
```

```{r}
K_limit=c(147.08,294.16)          
tailf=function(K,vol,x)       # set dK=1
{
  x=sort(c(x,x+1),decreasing=FALSE)
  vol_new=f(K,vol,x)
  price_ref=apply(cbind(x,vol_new), 1,Pricing)
  return(-exp(r*t)*(price_ref[2]-price_ref[1])/1)
}
tail_one=tailf(k[,1],vol[,1],K_limit[1])
tail_two=tailf(k[,1],vol[,1],K_limit[2])
P_within=tail_one-tail_two
CDF=1-tail_one
CDF_log=pnorm(log(K_limit[1]/s))
cat(P_within,CDF,CDF_log)
```
## Q2
```{r}
Put_delta=function(s,k,r,vol,t)
{
  d1=(log(s/k)+(r+vol^2/2)*t)/(vol*sqrt(t))
  return(pnorm(d1)-1)
}
numbers = read.csv("spx_87.csv")
numbers[,1] = as.numeric(as.Date('1987-08-01')-as.Date(numbers[,1],format='%m/%d/%Y'))/365
numbers[,3]=numbers[,3]/100
m=0.9
s0=numbers[1,2];r0=numbers[1,3]
k=s0*m;t=0.5
voltility=sqrt(var(diff(log(numbers[,2])))*252)
parameter=cbind(numbers[,2],numbers[,3],numbers[,1])
delta = Put_delta(s0,k,r0,voltility,t)
syn=-100/delta
for(i in 1:nrow(parameter))
{
  s_init=numbers[i,2];r_init=numbers[i,3];t_init=numbers[i,1]
  d=Put_delta(s_init,k,r_init,voltility,t_init)
  delta = c(delta,d)
  temp_num = -100/d
  syn=c(syn,temp_num)
}
print(delta) #here is the delta through time
```
```{r}
share = 100-syn
print(share) #here is the shares throught time 
```

